
development:
  adapter: postgresql
  database: emp_dev
  username: i4
  password: i4q2w3e4
  host: localhost
  #host: 192.168.20.151
  encoding: UTF8

test:
  adapter: postgresql
  database: emp_test
  username: i4
  password: i4q2w3e4
  host: localhost
  #host: 192.168.20.151
  encoding: UTF8

production:
  adapter: postgresql
  database: emprestimo
  username: i4
  password: i4q2w3e4
  #host: localhost
  host:  177.70.6.230
  encoding: UTF8
